### ISSUE TITLE
Listenbrainz support?

### ISSUE THREAD

**Issue by andrewgdunn** [GioF71/mpd-alsa-docker#391] opened 2024-04-05 23:17 UTC
Would you consider adding [this package](https://codeberg.org/elomatreb/listenbrainz-mpd) so that we could get scrobbling directly to listenbrainz?

**Comment by GioF71** [comment] 2024-04-06 10:24
Hello, that is definitely interesting but I see there are no packages for debian/ubuntu.
Anyway I can give it a try and maybe create a separate docker image for it.
I am particularly worried about including another package in the image for the following reasons

- this would increase build times considerably, especially if (as it seems) it's needed to compile from source
- image size would probably increase considerably as well
- There is already the (optionally) mpd-scribble application, something I don't already like: I'd prefer to keep one app per container

Would a separate container image work for you?

**Comment by GioF71** [comment] 2024-04-08 16:52
> Separate container image would be awesome!
> 
> > There is already the (optionally) mpd-scribble application, something I don't already like: I'd prefer to keep one app per container
> 
> As some feedback I think that you should consider removing this from the image and have scrobbling be in "sidecar" containers like you're doing with `mpd-subsonic-scrobbler`

Yes, I thought about it in the past, and in fact there is [this image](https://github.com/GioF71/mpd-scrobbler-docker) as well. I wonder if I will get issues opened if I remove the feature, even if I would be suggesting to use the other container... 
The problem is I don't know if anyone is using this "sidecar"!

**Comment by GioF71** [comment] 2024-04-13 10:03
Here: [Repo](https://github.com/GioF71/listenbrainz-mpd-docker).  
Images are building now, unfortunately it's a slow process, about 1h.
Will be waiting for your feedback!

**Comment by GioF71** [comment] 2024-04-19 06:22
Closing this as the repo is online. Will be waiting for your feedback for bug and/or feature requests.
Cheers

**Closed by GioF71** 2024-04-19 06:22 UTC
